export const ACTIONS = {
  UNDO: "UNDO",
  DELETE: "DELETE",
  REFRESH: "REFRESH",
  TOGGLE_LOCK: "TOGGLE_LOCK",
  MAKENODE: "MAKENODE",
  MAKEEDGE: "MAKEEDGE",
  CHANGEALGO: "CHANGEALGO",
  VISUALISE: "VISUALISE",
};
